auth/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

]

crowdfunding/urls.py
from authen import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authen.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('campaign/', include('campaign.urls')),
    path('user/', include('user.urls')),
    path('', include('home.urls')),
    path('comment/', include('comment.urls')),
    path('login/', auth_views.login),
]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'home.views.error_404'

user/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from . import views

urlpatterns = [
    path('profile/', views.profile, name="user_profile"),
    path('donations/', views.donations, name="user_donations"),
    path('edit/', views.edit, name='user_edit'),
    path('delete/', views.delete, name='user_delete'),
    path('check_password/', views.check_password, name='check_password')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.
PHONE_REGEX = RegexValidator(
    r'^01[0-2][0-9]{8}$', 'Egyptian phone number is required')


class UserManager(BaseUserManager):

    def create_user(self, email, first_name, last_name='', password=None, is_active=True, is_staff=False, is_admin=False):

        if not email:
            raise ValueError("Users must have an email address")
        if not password:
            raise ValueError("Users must have a password")
        if not first_name:
            raise ValueError("Users must have a first name")

        user_obj = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name
        )

        user_obj.set_password(password)  # change user password
        user_obj.is_staff = is_staff
        user_obj.is_admin = is_admin
        user_obj.is_active = is_active
        user_obj.save(using=self._db)

        return user_obj

    def create_staffuser(self, email, first_name, password=None):
        user = self.create_user(
            email,
            first_name=first_name,
            password=password,
            is_staff=True
        )
        return user

    def create_superuser(self, email, first_name, password=None):
        user = self.create_user(
            email,
            first_name=first_name,
            password=password,
            is_staff=True,
            is_admin=True
        )
        return user


class User (AbstractBaseUser, PermissionsMixin):

    # Essentials
    email = models.EmailField(
        max_length=255, verbose_name='email', unique=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    last_login = models.DateTimeField(
        blank=True, null=True, verbose_name='last login')
    date_joined = models.DateTimeField(auto_now_add=True)

    # Extras
    first_name = models.CharField(max_length=20, verbose_name='first name')
    last_name = models.CharField(
        max_length=20, default='',  verbose_name='last name')
    phone = models.CharField(max_length=15, validators=[
        PHONE_REGEX],  verbose_name='phone')
    avatar = models.ImageField(
        upload_to="profile_images", verbose_name='profile picture', default='profile_images/default-pic.jpeg')
    country = models.CharField(
        max_length=20, blank=True, default='',  verbose_name='country')
    birthdate = models.DateField(
        blank=True, null=True, verbose_name='birthdate')
    fb_account = models.URLField(blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name']
    EMAIL_FIELD = 'email'
    objects = UserManager()

    def __str__(self):
        return str(self.first_name + ' ' + self.last_name)

    def get_full_name(self):

        if self.__str__:
            return self.__str__
        return self.email

    def get_short_name(self):
        return self.first_name

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(
        upload_to="profile_images", verbose_name='profile picture', default='profile_images/default-pic.jpeg')

    def get_absolute_url(self):
        return reverse('user_profile')


def create_social_user(strategy, details, backend, user=None, *args, **kwargs):
    if user:
        return {'is_new': False}

    response = kwargs['response']

    if not details:
        return

    # create new user
    user = User.objects.create_user(email=details['email'], first_name=details['first_name'], last_name=details['last_name'],
                                    password="default@socail@password")

    # update user avatar

    # get avatar from google
    # if backend.name == "google-oauth2" and response.get('picture'):
    #     user.avatar = response.get('picture')
    #     print("here")
    #     print(response.get('picture'))

    # # get avatar from facebook
    # if backend.name == "facebook":
    #     user.avatar = response.get('picture').get('data').get('url')
    #     print("there", response.get('picture').get('data').get('url'))

    # user.save()

    # create user profile
    UserProfile.objects.create(user_id=user.id, avatar=user.avatar)

    return {
        'is_new': True,
        'user': user}

user/forms.py
from django import forms
from django.forms import ModelForm

from user.models import User


class EditForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone', 'avatar', 'birthdate', 'country', 'fb_account')

user/views.py
from campaign.models import Campaign, Donation
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import EditForm
from .models import User, UserProfile

# Create your views here.


@login_required
def profile(request):
    current_user_campaigns = Campaign.objects.filter(
        creator_id=request.user.id)
    return render(request, 'profile/base.html', {'campaigns': current_user_campaigns, 'donations': False})


@login_required
def donations(request):
    current_user_donations = Donation.objects.filter(
        donator_id=request.user.id)
    campaigns = Campaign.objects.all()
    return render(request, 'profile/base.html', {'current_user_donations': current_user_donations,
                                                 'campaigns': campaigns, 'donations': True})


@login_required
def edit(request):
    if request.method == "GET":
        current_user = request.user
        return render(request, 'user/edit.html', {'current_user': current_user})
    else:
        current_user = request.user
        profile = UserProfile.objects.get(user_id=current_user.id)
        form = EditForm(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            user = form.save()
            profile.avatar = user.avatar
            profile.save()
            return redirect('user_profile')
        return render(request, 'user/edit.html', {'current_user': current_user, 'form': form})


@login_required
def delete(request):
    request.user.delete()
    return redirect('logout')


@login_required
def check_password(request):
    if request.is_ajax and request.method == "POST":
        password = request.POST.get("pass")
        is_password_correct = request.user.check_password(password)
        return JsonResponse({"is_password_correct": is_password_correct})

user/templates/user/edit.html
{% extends 'layouts/base.html' %}

{% block title %} {{user}} {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
         style="min-height: 600px; background-image: url(/static/assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;">
      <!-- Mask -->
      <span class="mask bg-gradient-default opacity-8"></span>
      <!-- Header container -->
      <div class="container-fluid d-flex align-items-center">
        <div class="row">
          <div class="col-lg-7 col-md-10">
            <h1 class="display-2 text-white">Здравствуйте</h1>
            <h2 class="text-white">{{ current_user }}</h2>
            <p class="text-white mt-0 mb-5">Это страница вашего профиля. Вы можете просмотреть всю свою личную информацию</p>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid mt-7">
      <div class=" mb-3">
      </div>
      <div class="row justify-content-center">
        <div class="col-xl-8 order-xl-1">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-4">
                    <a href="{% url 'password_change'%}" class="btn btn-primary" role="button" for="id_password"> Изменить пароль</a>
                </div>
                <div class="col-4 mb-6">
                  <div class="card-profile-image">
                    <img src="..{{current_user.avatar.url}}" class="rounded-circle">
                  </div>
                </div>
                <div class="col-4 text-right">
                  <a class="btn btn btn-danger" data-toggle="modal" data-target="#deleteModal" style="color: white;">Удалить аккаунт</a>
                    <!-- Modal -->
                    <div class="modal" tabindex="-1" role="dialog" id="deleteModal">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title">Подтверждающее сообщение</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body" id="modalBody">
                            <p class="text-left"> Введите пароль для подтверждения</p>
                            <div class="align-content-start">
                            <input id="passwordConfirmation" type="password" class="form-control form-control-alternative" placeholder="Enter password">
                          </div>
                          </div>
                          <div class="modal-footer">
                            <button id="submitPassword" type="button" class="btn btn-primary">Приступайте</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Прервать</button>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
              </div>
            </div>
            <div class="card-body">
              <form action="{% url 'user_edit' %}" method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                <h6 class="heading-small text-muted mb-4">Информация о пользователе</h6>
                <div class="pl-lg-4">

                  <div class="">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Email</label>
                        <input type="email" id="input-email" class="form-control form-control-alternative"
                               placeholder="{{ current_user.email }}" readonly>
                      </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="id_first_name">Имя</label>
                        <input type="text" name="first_name" id="id_first_name" class="form-control form-control-alternative"
                        value="{{current_user.first_name}}" maxlength="20" required>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="id_last_name">Фамилия</label>
                        <input type="text" name="last_name" id="id_last_name" class="form-control form-control-alternative"
                        value="{{current_user.last_name}}" maxlength="20" required >
                      </div>
                    </div>
                  </div>
                        <div class="row">
                    <div class="col-lg-6">

                    </div>
                  </div>
                </div>
                <hr class="my-4" />
                <!-- Address -->
                <h6 class="heading-small text-muted mb-4">Контактная информация</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="id_phone">Телефон</label>
                        <input id="id_phone" name="phone" class="form-control form-control-alternative" value="{{current_user.phone}}" type="text"
                        maxlength="15" required>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="id_fb_account">Facebook </label>
                        <input id="id_fb_account" name="fb_account" class="form-control form-control-alternative" value="{{current_user.fb_account}}" type="url">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="id_avatar">Аватарка</label>
                        <input type="file" accept="image/*" name="avatar" id="id_avatar" class="form-control form-control-alternative"
                               value="{{current_user.avatar}}">
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="id_country">Страна</label>
                        <input type="text" name="country" id="id_country" class="form-control form-control-alternative"
                               value="{{current_user.country}}" maxlength="20">
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="id_birthdate">Дата рождения</label>
                        <input id="id_birthdate" name="birthdate" class="form-control form-control-alternative" value="{{current_user.birthdate|date:'Y-m-d'}}" type="date">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="d-flex justify-content-center">
                <div class="w-75 text-center">
                {% for field in form %}
                  {% for error in field.errors %}
                    <li class="alert alert-danger">{{ error }}</li><br>
                  {% endfor %}
                {% endfor %}
              </div>
            </div>
                <div class="row justify-content-center">
                  <button type="submit" class="btn btn-info">Изменить профиль</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>

      {% include "includes/footer.html" %}

    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script>
  $(document).ready(function() {
    $("#submitPassword").on('click', submit)
  })

  function submit(e){
    let password = $('#passwordConfirmation').val();
    if (password) {
      sendRequest(password);
    }
  }

  function sendRequest(password){
    $.ajax({
      url:"{% url 'check_password' %}",
      type: "POST",
      data: {pass: password, csrfmiddlewaretoken: '{{ csrf_token }}'},
      dataType: "JSON",
      success: handleSuccess
    })
  }

  function handleSuccess(result){
    isPasswordCorrect = JSON.parse(result["is_password_correct"]);
    if (! isPasswordCorrect ){
      $("#modalBody").append("<div class='d-flex justify-content-center mt-4'><p class='alert alert-danger text-center w-75'>Password is not correct</p></div>")
    }
    else{
      window.location.href = "{% url 'user_delete' %}"
    }
  }
</script>
{% endblock javascripts %}